# Generated by Django 3.1.7 on 2021-03-21 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PbsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_name', models.CharField(max_length=50)),
                ('pbs_name_benglai', models.CharField(max_length=50)),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.TextField(blank=True, null=True)),
                ('management_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.managementinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PbsInfoBERC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_nos', models.IntegerField(blank=True, null=True)),
                ('complain_solve', models.IntegerField(blank=True, null=True)),
                ('complain_unsolve_case', models.TextField(blank=True, max_length=300, null=True)),
                ('complain_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('pbs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoapp.pbsinfo')),
            ],
        ),
    ]
