# Generated by Django 3.1.7 on 2021-03-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedConsumerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('domestic', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('commercial', models.CharField(blank=True, max_length=250, null=True)),
                ('irrigation', models.CharField(blank=True, max_length=250, null=True)),
                ('govt_institute', models.CharField(blank=True, max_length=250, null=True)),
                ('other', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('taken_action', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DcConsumerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('domestic', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('commercial', models.CharField(blank=True, max_length=250, null=True)),
                ('irrigation', models.CharField(blank=True, max_length=250, null=True)),
                ('govt_institute', models.CharField(blank=True, max_length=250, null=True)),
                ('other', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('taken_action', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticConnectionSevenDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_app', models.CharField(blank=True, max_length=250, null=True)),
                ('con_within_seven_day_app', models.CharField(blank=True, max_length=250, null=True)),
                ('con_without_seven_day_app', models.CharField(blank=True, max_length=250, null=True)),
                ('process_seven_day_app', models.CharField(blank=True, max_length=250, null=True)),
                ('reason_not_con_of_seven_day', models.TextField(blank=True, max_length=250, null=True)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCommercialDcRc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_dc_app', models.CharField(blank=True, max_length=250, null=True)),
                ('total_app_get_for_rc', models.CharField(blank=True, max_length=250, null=True)),
                ('complete_rc_app', models.CharField(blank=True, max_length=250, null=True)),
                ('illegal_app_for_dc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCoordinationMeetingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('consumer_meeting_nos', models.CharField(blank=True, max_length=250, null=True)),
                ('previous_month_unsolve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('current_month_unsolve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('total_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('current_month_solve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('unsolve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NecessaryActionAgainstAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('shift_cable', models.CharField(blank=True, max_length=250, null=True)),
                ('install_pole_for_unshift_cable', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_cable_for_non_install_pole', models.CharField(blank=True, max_length=250, null=True)),
                ('span_length_sag_visit', models.CharField(blank=True, max_length=250, null=True)),
                ('risk_unfit_pole_change', models.CharField(blank=True, max_length=250, null=True)),
                ('pdb_risk_pole_check_change', models.CharField(blank=True, max_length=250, null=True)),
                ('electric_line_maintainance_by_instraction', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewOnlineConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_app', models.CharField(blank=True, max_length=250, null=True)),
                ('total_solve_app', models.CharField(blank=True, max_length=250, null=True)),
                ('cause_of_unsolve', models.TextField(blank=True, max_length=250, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PbsInfoBERC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('complain_nos', models.CharField(blank=True, max_length=250, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('complain_solve', models.CharField(blank=True, max_length=250, null=True)),
                ('complain_unsolve_case', models.TextField(blank=True, max_length=300, null=True)),
                ('complain_remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PbsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_name', models.CharField(max_length=50)),
                ('pbs_name_benglai', models.CharField(max_length=50)),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.TextField(blank=True, null=True)),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infoapp.managementinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
