# Generated by Django 3.2.6 on 2021-10-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterDataReadDhakapbs1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time_date', models.CharField(blank=True, max_length=100, null=True)),
                ('hex', models.CharField(blank=True, max_length=100, null=True)),
                ('kwh', models.CharField(blank=True, max_length=100, null=True)),
                ('kwh2', models.CharField(blank=True, max_length=100, null=True)),
                ('kvarh', models.CharField(blank=True, max_length=100, null=True)),
                ('kvarh2', models.CharField(blank=True, max_length=100, null=True)),
                ('kvah', models.CharField(blank=True, max_length=100, null=True)),
                ('avah2', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage1', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage2', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage3', models.CharField(blank=True, max_length=100, null=True)),
                ('current1', models.CharField(blank=True, max_length=100, null=True)),
                ('current2', models.CharField(blank=True, max_length=100, null=True)),
                ('current3', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feeder_no', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
