# Generated by Django 3.1.7 on 2021-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_managementinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementinfo',
            old_name='m_id',
            new_name='management_code',
        ),
        migrations.RenameField(
            model_name='managementinfo',
            old_name='m_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='managementinfo',
            name='management_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='managementinfo',
            name='name_bengali',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
