# Generated by Django 3.1.7 on 2021-08-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_remove_meterdataread_date_timee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdataread',
            name='pbs_code',
        ),
    ]
