# Generated by Django 3.1.7 on 2021-03-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_remove_pbsinfoberc_pbs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsinfoberc',
            name='pbs_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
