# Generated by Django 3.1.7 on 2021-03-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0003_pbsinfoberc_pbs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsinfoberc',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pbsinfoberc',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
