# Generated by Django 3.1.7 on 2021-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0003_auto_20210323_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsinfo',
            name='management',
        ),
        migrations.AddField(
            model_name='pbsinfo',
            name='management_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
