# Generated by Django 3.1.7 on 2021-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0004_auto_20210321_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsinfo',
            name='management_name',
        ),
        migrations.AddField(
            model_name='pbsinfo',
            name='management_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
