# Generated by Django 3.1.7 on 2021-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0004_auto_20210324_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsinfo',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
