# Generated by Django 3.1.7 on 2021-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0005_auto_20210324_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsinfoberc',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
