# Generated by Django 3.1.7 on 2021-03-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0005_auto_20210321_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbsinfo',
            name='management_id',
        ),
        migrations.AddField(
            model_name='pbsinfo',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infoapp.managementinfo'),
        ),
    ]
