# Generated by Django 3.1.7 on 2021-03-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0006_pbsinfoberc_management_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedconsumerinfo',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcconsumerinfo',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domesticconnectionsevenday',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrycommercialdcrc',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycoordinationmeetinginfo',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necessaryactionagainstaccident',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newonlineconnection',
            name='management_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
