# Generated by Django 3.1.7 on 2021-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0007_auto_20210324_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
