# Generated by Django 3.1.7 on 2021-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0009_auto_20210321_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_app', models.IntegerField(blank=True, null=True)),
                ('total_solve_app', models.IntegerField(blank=True, null=True)),
                ('cause_of_unsolve', models.TextField(blank=True, max_length=250, null=True)),
                ('remark', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
