# Generated by Django 3.1.7 on 2021-03-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0010_newconnection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewConnection',
            new_name='NewOnlineConnection',
        ),
    ]
