# Generated by Django 3.1.7 on 2021-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0012_newonlineconnection_pbs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newonlineconnection',
            name='month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newonlineconnection',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
