# Generated by Django 3.1.7 on 2021-03-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0013_auto_20210321_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newonlineconnection',
            name='total_app',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='newonlineconnection',
            name='total_solve_app',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
