# Generated by Django 3.1.7 on 2021-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0015_auto_20210322_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCommercialDcRc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_dc_app', models.CharField(blank=True, max_length=250, null=True)),
                ('total_app_get_for_rc', models.CharField(blank=True, max_length=250, null=True)),
                ('complete_rc_app', models.CharField(blank=True, max_length=250, null=True)),
                ('illegal_app_for_dc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
