# Generated by Django 3.1.7 on 2021-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0016_industrycommercialdcrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcConsumerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('domestic', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('commercial', models.CharField(blank=True, max_length=250, null=True)),
                ('irrigation', models.CharField(blank=True, max_length=250, null=True)),
                ('govt_institute', models.CharField(blank=True, max_length=250, null=True)),
                ('other', models.CharField(blank=True, max_length=250, null=True)),
                ('total_dc_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('taken_action', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
