# Generated by Django 3.1.7 on 2021-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0017_dcconsumerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedConsumerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('domestic', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('commercial', models.CharField(blank=True, max_length=250, null=True)),
                ('irrigation', models.CharField(blank=True, max_length=250, null=True)),
                ('govt_institute', models.CharField(blank=True, max_length=250, null=True)),
                ('other', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('taken_action', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticConnectionSevenDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('total_app', models.CharField(blank=True, max_length=250, null=True)),
                ('con_within_seven_day_app', models.CharField(blank=True, max_length=250, null=True)),
                ('con_without_seven_day_app', models.CharField(blank=True, max_length=250, null=True)),
                ('process_seven_day_app', models.CharField(blank=True, max_length=250, null=True)),
                ('reason_not_con_of_seven_day', models.TextField(blank=True, max_length=250, null=True)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dcconsumerinfo',
            old_name='total_dc_amount',
            new_name='total_amount',
        ),
    ]
