# Generated by Django 3.1.7 on 2021-03-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0018_auto_20210322_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCoordinationMeetingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('consumer_meeting_nos', models.CharField(blank=True, max_length=250, null=True)),
                ('previous_month_unsolve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('current_month_unsolve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('total_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('current_month_solve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('unsolve_objection', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
