# Generated by Django 3.1.7 on 2021-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0019_monthlycoordinationmeetinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessaryActionAgainstAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbs_code', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('shift_cable', models.CharField(blank=True, max_length=250, null=True)),
                ('install_pole_for_unshift_cable', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_cable_for_non_install_pole', models.CharField(blank=True, max_length=250, null=True)),
                ('span_length_sag_visit', models.CharField(blank=True, max_length=250, null=True)),
                ('risk_unfit_pole_change', models.CharField(blank=True, max_length=250, null=True)),
                ('pdb_risk_pole_check_change', models.CharField(blank=True, max_length=250, null=True)),
                ('electric_line_maintainance_by_instraction', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
