# Generated by Django 3.1.7 on 2021-03-23 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoapp', '0020_necessaryactionagainstaccident'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
