# Generated by Django 3.1.7 on 2021-03-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0022_auto_20210323_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementinfo',
            name='user',
        ),
    ]
