# Generated by Django 3.1.7 on 2021-03-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0023_remove_managementinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementinfo',
            name='user_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
